name: Build Image

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - "main"
      - "*.*.*"
  pull_request: {}


jobs:
  envs:
    runs-on: ubuntu-latest
    outputs:
      build-args: ${{ steps.prepare-envs.outputs.build-args }}
      tags: ${{ steps.create-tags.outputs.tags }}
      envs: ${{ steps.prepare-envs.outputs.* }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set build mode
        run: |
          echo $GITHUB_REF_NAME
          if [[ $GITHUB_EVENT_NAME == 'push' && $GITHUB_REF_NAME == release* ]]; then
            echo "BUILD_MODE=release" >> "$GITHUB_ENV"
          else
            echo "BUILD_MODE=PR" >> "$GITHUB_ENV"
          fi

      - name: prepare envs
        id: prepare-envs
        run: |
          {
          echo 'build-args<<BUILD_ARGS'
          echo "BUILD_MODE=${{ env.BUILD_MODE }}"
          cat otel-collector/envs
          echo BUILD_ARGS 
          } >> "$GITHUB_OUTPUT"

      - name: load envs into output
        id: load-envs
        run: |
          cat otel-collector/envs >> "$GITHUB_OUTPUT"

      - name: print env context
        run: echo "${{ steps.prepare-envs.outputs.build-args }}"

      - name: create tags
        id: create-tags
        run: |
          if [[ $GITHUB_EVENT_NAME == 'push' ]]; then
            echo 'TAGS="${{ steps.load-envs.outputs.OTEL_VERSION }}-${{ github.ref_name }}"' >> "$GITHUB_OUTPUT"
          else
            echo 'TAGS="PR-${{ github.event.pull_request.number }}"' >> "$GITHUB_OUTPUT"
          fi

  build-image:
    needs: envs
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: kyma-otel-collector
      dockerfile: otel-collector/Dockerfile
      context: .
      build-args: ${{ needs.envs.outputs.build-args }}
      tags: ${{ needs.envs.outputs.tags }}

  debug:
    needs: envs
    runs-on: ubuntu-latest
    steps:
      - name: print variables
        run: |
          echo "${{ needs.envs.outputs.build-args }}"
          echo "${{ needs.envs.outputs.tags }}"
          echo "${{ needs.envs.outputs.envs }}"


