name: Build Image

on:
  pull_request_target:
    types: [ opened, edited, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - "main"
      - "release-*"

jobs:
  envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set build mode
        run: |
          BRANCH=$(echo $GITHUB_REF | cut -d'/' -f 3)
          if [[ $GITHUB_EVENT_NAME == 'push' && $BRANCH == release* ]]; then
            echo "BUILD_MODE=release" >> "$GITHUB_ENV"
          else
            echo "BUILD_MODE=PR" >> "$GITHUB_ENV"
          fi

      - name: prepare envs
        id: prepare-envs
        run: |
          {
          echo 'build-args<<BUILD_ARGS'
          echo "BUILD_MODE=${{ env.BUILD_MODE }}"
          cat otel-collector/envs
          echo BUILD_ARGS 
          } >> "$GITHUB_OUTPUT"

      - name: print env context
        run: echo "${{ steps.prepare-envs.outputs.build-args }}"

  build-image:
    needs: envs
    uses: kyma-project/test-infra/.github/workflows/image-builder.yml@main # Usage: kyma-project/test-infra/.github/workflows/image-builder.yml@main
    with:
      name: kyma-otel-collector
      dockerfile: otel-collector/Dockerfile
      context: .
      build-args: ${{ needs.envs.outputs.build-args }}
      tags: bla


